services:
  - type: web
    name: birthday-gift-api
    env: docker
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 8080
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_BOT_USERNAME
        sync: false
      - key: TELEGRAM_ADMIN_CHAT_ID
        sync: false